[project]
name = "agent-core-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore>=1.2.1",
    "boto3>=1.42.45",
    "pyyaml>=6.0.3",
]

